Adding NoSuchMethodError to catch blocks (#2719)
### Summary
The UIAutomation tests failed due to uncaught NoSuchMethodErrors. The
methods I added as a part of my Baggage PRs do have catch blocks meant
for this purpose, but they were catching a generic exception (which
NoSuchMethodError does not fall into).